Token Logic
cesium/safira pull request #153
Opened 2021-02-07 16:18 UTC by tsource98

2021-02-07 16:32 UTC, joaop21 requested changes
You should run `mix format` against the changed files.

2021-02-07 16:32 UTC, joaop21 commented on lib/mix/tasks/gen.badges.ex
> +          tokens: tokens
tokens should be casted to integer

2021-02-07 16:32 UTC, joaop21 commented on lib/safira/contest/badge.ex
>      |> validate_required([:begin, :end, :name, :description, :type])
should include `:tokens`

2021-02-07 16:32 UTC, joaop21 commented on lib/safira_web/views/attendee_view.ex
> +      total_tokens: attendee.total_tokens,
I think token_balance would be more adequate.

2021-02-07 16:32 UTC, joaop21 commented on lib/safira_web/views/attendee_view.ex
> +      total_tokens: attendee.total_tokens,
same as above

2021-02-07 16:35 UTC, jpcorreia99 commented on mix.exs
>    # Specifies which paths to compile per environment.
I think this was, probably, a misclick.

2021-02-07 17:42 UTC, tsource98 commented
Guess your comments are now fixed. Feel free to suggest anything else

2021-02-07 17:48 UTC, jpcorreia99 approved these changes
:shipit:

2021-02-08 11:37 UTC, joaop21 requested changes

2021-02-08 11:37 UTC, joaop21 commented on priv/repo/migrations/20210120134552_add_tokens_badge.exs
> +end
You should run `mix format priv/repo/migrations/20210120134552_add_tokens_badge.exs`

2021-02-08 11:37 UTC, joaop21 commented on priv/repo/migrations/20210207173118_add_token_balance_attendee.exs
> +end
You should run `priv/repo/migrations/20210207173118_add_token_balance_attendee.exs`

2021-02-08 18:54 UTC, jpcorreia99 approved these changes

2021-02-08 18:57 UTC, joaop21 approved these changes

2021-02-08 18:57 UTC, merged