build: Migrate views to Phoenix 1.7
cesium/safira pull request #343
Opened 2023-09-07 11:12 UTC by ruioliveira02

2023-09-10 13:59 UTC, RuiL1904 commented
@ruioliveira02 I agree.

2023-09-14 13:43 UTC, MarioRodrigues10 requested changes

2023-09-14 13:43 UTC, MarioRodrigues10 commented on lib/safira_web/controllers/fallback_controller.ex
> +
```suggestion


```

2023-11-28 19:41 UTC, MarioRodrigues10 requested changes

2023-11-28 19:41 UTC, MarioRodrigues10 commented on lib/safira_web/controllers/attendee/attendee_json.ex
> +      redeemables: for(r <- at.redeemables, do: RedeemableJSON.my_readeemables(%{redeemable: r}))
```suggestion
      redeemables: for(r <- at.redeemables, do: RedeemableJSON.my_redeemables(%{redeemable: r}))
```
Fix the typo in this line

2023-11-29 16:35 UTC, MarioRodrigues10 requested changes
It returns the following error:
![image](https://github.com/cesium/safira/assets/93675410/30cd3058-a24f-4ea3-a9e9-377e9c74e41d)
![image](https://github.com/cesium/safira/assets/93675410/46acc8f6-035b-4e29-b776-adfa1b43ba14)

2023-11-29 16:38 UTC, MarioRodrigues10 commented on lib/safira_web/controllers/roulette/roulette_json.ex
> -  end
I think is due to this function you should create
```elixir
def price(%{price: price}) do
 %{price: price}
end

```

2024-10-13 19:49 UTC, joaodiaslobo commented
No longer applicable.

2024-10-13 19:49 UTC, closed without merging