feat: block routes based on event start time
cesium/safira pull request #431
Opened 2024-11-04 17:45 UTC by ruioliveira02

2024-11-10 16:21 UTC, MarioRodrigues10 requested changes

2024-11-10 16:21 UTC, MarioRodrigues10 commented on lib/safira_web/router.ex
> +        pipe_through [:require_credential]
You can't have 2 `pipe_through` like this

2024-11-10 16:21 UTC, MarioRodrigues10 commented on lib/safira_web/gettext.ex
Due to some changes in gettext, now it's not working in `user_roles`

2024-11-10 16:22 UTC, MarioRodrigues10 commented
In case start_time is `2025-11-29T17:57:00Z` which routes should i have access to when i access the app?

2024-11-18 13:32 UTC, MarioRodrigues10 requested changes

2024-11-18 13:32 UTC, MarioRodrigues10 commented on lib/safira_web/live/backoffice/event_live/form_component.ex
> +  end
This should be in a helpers module

2024-11-18 13:32 UTC, MarioRodrigues10 commented on lib/safira_web/live/backoffice/event_live/form_component.ex
> +    Event.change_event_start_time(parse_date(params["start_time"]))
What if this doesn't return `:ok`

2024-11-18 13:32 UTC, MarioRodrigues10 commented on lib/safira_web/live/app/waiting_live/index.ex
> +       |> push_navigate(to: ~p"/app")}
```suggestion
      {:ok, push_navigate(socket, to: ~p"/app")}
```

2024-11-18 13:32 UTC, MarioRodrigues10 commented on priv/repo/seeds/constants.exs
> +  end
Just a reminder to change this.

2024-11-20 09:48 UTC, MarioRodrigues10 requested changes

2024-11-27 19:14 UTC, MarioRodrigues10 submitted a review, later dismissed
:rocket:

2025-01-02 22:43 UTC, joaodiaslobo approved these changes

2025-01-02 22:43 UTC, merged