Spotlights
cesium/safira pull request #438
Opened 2024-11-12 18:43 UTC by AfonsoMartins26

2025-01-09 22:30 UTC, joaodiaslobo requested changes

2025-01-09 22:30 UTC, joaodiaslobo commented on lib/safira/spotlights.ex
> +    case Constants.get("duration_spotlights") do
```suggestion
  def get_spotlight_duration do
    case Constants.get("spotlight_duration") do
```

2025-01-09 22:30 UTC, joaodiaslobo commented on lib/safira_web/components/banner.ex
> +  end
```suggestion
  attr :text, :string, default: ""
  attr :duration, :integer, default: 5000

  def banner(assigns) do
    ~H"""
    <div
      id="banner"
      phx-hook="Banner"
      class="relative w-full bg-white text-center p-4 text-black font-bold shadow-lg z-10 transition-transform transform"
      style="top: 0;"
      data-duration={@duration}
    >
      <p><%= @text %></p>
      <div id="timer-countdown" phx-hook="Timer" data-finish-time={DateTime.to_unix(@duration)}>
        00:00:00
      </div>
    </div>
    """
  end
```

2025-01-09 22:30 UTC, joaodiaslobo commented on lib/safira_web/components/layouts.ex
> +  import SafiraWeb.Landing.Components.Footer
```suggestion
  import SafiraWeb.Landing.Components.{Footer, Navbar, Sparkles}
```

2025-01-09 22:30 UTC, joaodiaslobo commented on lib/safira_web/live/backoffice/spotlights_live/confirm.ex
> +              "Are you sure you want to start a spotlight for %{company_name} with a duration of %{duration} %{unit}.",
```suggestion
              "Are you sure you want to start a spotlight for %{company_name} with a duration of %{duration} %{unit}?",
```

2025-01-09 22:30 UTC, joaodiaslobo commented on lib/safira/companies/tier.ex
> +  def changeset_multiplier(tier, attrs) do
```suggestion
  def changeset_spotlight_configuration(tier, attrs) do
```

2025-01-09 22:30 UTC, joaodiaslobo commented on lib/safira/spotlights.ex
> +  def get_duration do
```suggestion
  def get_spotlight_duration do
```

2025-01-09 22:30 UTC, joaodiaslobo commented on lib/safira_web/live/backoffice/spotlights_live/confirm.ex
> +      case Spotlights.create_spotlight(attrs) do
```suggestion
      case Spotlights.create_spotlight(socket.assigns.company_id) do
```

2025-01-09 22:30 UTC, joaodiaslobo commented on lib/safira_web/live/backoffice/spotlights_live/index.html.heex
> +  id="spotlight-confirm"
```suggestion
  id="spotlight-confirm-modal"
```

2025-01-09 22:30 UTC, joaodiaslobo commented on lib/safira_web/live/backoffice/spotlights_live/index.html.heex
> +  id="tiers-config"
```suggestion
  id="tiers-config-modal"
```

2025-01-09 22:30 UTC, joaodiaslobo commented on lib/safira_web/live/backoffice/spotlights_live/index.html.heex
> +  id="spotlight-config"
```suggestion
  id="spotlight-config-modal"
```

2025-01-09 22:30 UTC, joaodiaslobo commented on mix.lock
> +  "fontawesome": {:git, "https://github.com/FortAwesome/Font-Awesome.git", "37eff7fa00de26db41183a3ad8ed0e9119fbc44b", [tag: "6.6.0", sparse: "svgs"]},
```suggestion
  "fontawesome": {:git, "https://github.com/FortAwesome/Font-Awesome.git", "37eff7fa00de26db41183a3ad8ed0e9119fbc44b", [tag: "6.6.0", sparse: "svgs", depth: 1]},
```

2025-01-09 22:30 UTC, joaodiaslobo commented on mix.lock
> +  "heroicons": {:git, "https://github.com/tailwindlabs/heroicons.git", "88ab3a0d790e6a47404cba02800a6b25d2afae50", [tag: "v2.1.1", sparse: "optimized"]},
```suggestion
  "heroicons": {:git, "https://github.com/tailwindlabs/heroicons.git", "88ab3a0d790e6a47404cba02800a6b25d2afae50", [tag: "v2.1.1", sparse: "optimized", depth: 1]},
```

2025-01-09 22:30 UTC, joaodiaslobo commented on priv/repo/migrations/20241004172259_create_tiers.exs
> +      add :multiplier, :float, null: false
```suggestion
      add :spotlight_multiplier, :float, null: false
```

2025-01-09 22:30 UTC, joaodiaslobo commented on lib/safira_web/live/backoffice/spotlights_live/tiers/index.ex
> +  end
```suggestion
```

2025-01-09 22:30 UTC, joaodiaslobo commented on lib/safira_web/live/backoffice/spotlights_live/tiers/index.ex
> +            id={"tier-" <> tier.id}
```suggestion
            :for={{id, tier} <- @streams.tiers}
            id={id}
```

2025-01-09 22:59 UTC, AfonsoMartins26 commented on lib/safira/companies.ex
> +    current_spotlights_count <= tier.max_spotlights
I dont think so ,because if the company gets only one spotlight what we do in the case of changing to less than equal , we are putting the number of max spotlights at 2, i thinks its better the number of max spotlights be the number of possible spotlights, what do you think ?

2025-01-12 22:46 UTC, joaodiaslobo commented on lib/safira/companies.ex
> +    current_spotlights_count <= tier.max_spotlights
The problem with the current code is the following:
Let's say Company A is Gold tier, and Gold tier has only 2 spotlights, so **max spotlights is 2**.
When the event starts Company A has 0 spotlights.
- When we trigger the first spotlight for Company A, the following will be checked: **current_spotlights_count (0) <= max_spotlights (2)**? True! So the spotlight is activated.
- When we trigger the second spotlight for Company A, the following will be checked: **current_spotlights_count (1) <= max_spotlights (2)**? True! So the spotlight is activated.
(note that the company should not have more spotlights now, because it already got two)
- Hypothetically,  when we trigger a third spotlight for Company A, the following will be checked: **current_spotlights_count (2) <= max_spotlights (2)**? True! So a **third spotlight will be activated**. We don't want that!
Therefore, the condition should be: `current_spotlights_count < tier.max_spotlights`

2025-01-13 00:30 UTC, AfonsoMartins26 commented on lib/safira/companies.ex
> +    current_spotlights_count <= tier.max_spotlights
Ok, I understand it now. 👍

2025-01-13 23:50 UTC, joaodiaslobo requested changes

2025-01-13 23:50 UTC, joaodiaslobo commented on lib/safira/spotlights.ex
> +    subscribe_to_spotlight_event()
```suggestion
```

2025-01-13 23:55 UTC, joaodiaslobo commented
Please add the following to the company schema (company.ex):
```
    has_many :spotlights, Safira.Spotlights.Spotlight
```

2025-01-14 13:54 UTC, joaodiaslobo commented
I don't know why but the app is crashing when the spotlight ends for an attendee.

2025-01-19 16:53 UTC, joaodiaslobo requested changes
Now it's crashing when a spotlight gets created.

![image](https://github.com/user-attachments/assets/2f0875f6-e263-47a8-8e36-0ce10b133fbe)

2025-01-19 16:56 UTC, joaodiaslobo requested changes

2025-01-19 16:56 UTC, joaodiaslobo commented on lib/safira_web/live/app/home_live/index.ex
> +  end
This is odd, the home page shouldn't be handling the spotlight end event.

2025-01-22 23:27 UTC, AfonsoMartins26 commented on lib/safira_web/live/app/home_live/index.ex
> +  end
i thinks its is from the hook the banner one

2025-01-28 02:46 UTC, joaodiaslobo requested changes

2025-01-28 02:46 UTC, joaodiaslobo commented on assets/js/app.js
> +import { QrScanner, Wheel, Confetti, Countdown, Sorting, CoinFlip, Redirect, CredentialScene,Timer ,Banner} from "./hooks";
```suggestion
import { QrScanner, Wheel, Confetti, Countdown, Sorting, CoinFlip, Redirect, CredentialScene, Banner} from "./hooks";
```

2025-01-28 02:46 UTC, joaodiaslobo commented on assets/js/app.js
>    Confetti: Confetti,
```suggestion
  Wheel: Wheel,
  Countdown: Countdown,
  Confetti: Confetti,
```

2025-01-28 02:46 UTC, joaodiaslobo commented on assets/js/app.js
> +  Timer: Timer,
```suggestion
```

2025-01-28 02:46 UTC, joaodiaslobo commented on assets/js/hooks/banner.js
> +};
```suggestion
export const Banner = {
  mounted() {
    bannerLogic(this.el, new Date(banner.getAttribute("data-end")));
  },

  updated() {
    bannerLogic(this.el, new Date(banner.getAttribute("data-end")));
  }
};

function bannerLogic(banner, endTime) {      
  banner.style.transition = "top 0.5s ease-in-out";
  banner.style.top = "0";

  // Hide the banner after the duration
  setTimeout(() => {
    banner.style.transition = "top 0.5s ease-in-out";
    banner.style.top = "-100px";
  }, (endTime - Date.now()));


  const countdownElement = banner.querySelector("#timer-countdown");

  // Update banner timer
  countdownInterval = setInterval(() => {
    const now = Date.now();
    const secondsLeft = Math.round((endTime - now) / 1000);

    if (secondsLeft >= 0) {
      countdownElement.textContent = formatTime(secondsLeft);
    } 
  }, 100);
}

function formatTime(totalSeconds) {
  const dayToSeconds = 86400;
  const days = Math.floor(totalSeconds / dayToSeconds);
  const hours = Math.floor((totalSeconds % dayToSeconds) / 3600);
  const minutes = Math.floor((totalSeconds % 3600) / 60);
  const seconds = totalSeconds % 60;

  const formattedTime = [
      days > 0 ? `${days} days` : null,
      `${String(hours).padStart(2, '0')}:${String(minutes).padStart(2, '0')}:${String(seconds).padStart(2, '0')}`
  ].filter(Boolean).join(", ");

  return formattedTime;
}
```

2025-01-28 02:46 UTC, joaodiaslobo commented on assets/js/hooks/index.js
> +export { Timer } from "./time.js";
```suggestion
```

2025-01-28 02:46 UTC, joaodiaslobo commented on assets/js/hooks/time.js
You can delete this hook, let's use the existing countdown one!

2025-01-28 02:46 UTC, joaodiaslobo commented on lib/safira_web/components/banner.ex
> +end
```suggestion
defmodule SafiraWeb.Components.Banner do
  @moduledoc false
  use SafiraWeb, :component

  attr :text, :string, default: ""
  attr :end_time, :any, default: nil

  def banner(assigns) do
    ~H"""
    <div
      id="banner"
      phx-hook="Banner"
      class="relative w-full bg-white text-center p-4 text-black font-bold shadow-lg z-10 transition-transform transform"
      data-end={@end_time}
    >
      <p><%= @text %></p>
      <div id="timer-countdown">
        --:--:--
      </div>
    </div>
    """
  end
end
```

2025-01-28 02:46 UTC, joaodiaslobo commented on lib/safira_web/components/layouts/app.html.heex
> +        duration={@current_spotlight.end}
```suggestion
        end_time={@current_spotlight.end}
```

2025-01-28 02:46 UTC, joaodiaslobo commented on lib/safira_web/live/app/home_live/index.ex
> +  end
```suggestion
  @impl true
```

2025-01-28 02:46 UTC, joaodiaslobo commented on lib/safira_web/live/backoffice/spotlights_live/index.ex
> +    {:ok, socket |> assign(:spotlight, Spotlights.get_current_spotlight())}
```suggestion
    case Spotlights.get_current_spotlight() do
      nil -> {:ok, socket |> assign(:current_spotlight, nil)}
      spotlight ->
        {:ok, socket
              |> assign(:current_spotlight, spotlight)
              |> push_event("start-countdown", %{end_time: spotlight.end})}
    end
```

2025-01-28 02:46 UTC, joaodiaslobo commented on lib/safira_web/live/backoffice/spotlights_live/index.ex
> +  end
```suggestion
```

2025-01-28 02:46 UTC, joaodiaslobo commented on lib/safira_web/live/backoffice/spotlights_live/index.html.heex
> +    <% else %>
```suggestion
    <%= if @current_spotlight do %>
      <p>
        <%= gettext("%{company_name} is on spotlight!", company_name: @current_spotlight.company.name) %>
      </p>
      <div
        id="seconds-remaining"
        phx-hook="Countdown"
      >
        --:--:--
      </div>
    <% else %>
```

2025-01-28 22:57 UTC, joaodiaslobo requested changes

2025-01-28 22:57 UTC, joaodiaslobo commented on assets/js/hooks/countdown.js
> +
```suggestion
```

2025-01-28 22:57 UTC, joaodiaslobo commented on assets/js/hooks/countdown.js
> +            startCountdown(time);
```suggestion
        this.handleEvent("start-countdown", (data) => {
            const time = new Date (data.end_time).getTime();
            startCountdown(time);
```

2025-01-28 22:57 UTC, joaodiaslobo commented on assets/js/hooks/countdown.js
> +            startCountdown(time);
Attention!! `data` not `date`

2025-01-28 22:58 UTC, joaodiaslobo commented on lib/safira_web/components/banner.ex
> +end
Don't forget to change the argument to be `:end_time`, not `:duration`!

2025-01-29 22:48 UTC, joaodiaslobo requested changes

2025-01-29 22:48 UTC, joaodiaslobo commented on assets/js/app.js
> +import { QrScanner, Wheel, Confetti, Countdown, Sorting, CoinFlip, Redirect, CredentialScene ,Banner} from "./hooks";
```suggestion
import { QrScanner, Wheel, Confetti, Countdown, Sorting, CoinFlip, Redirect, CredentialScene, Banner } from "./hooks";
```

2025-01-29 22:48 UTC, joaodiaslobo commented on lib/safira/companies.ex
> +
Can you add documentation to the public functions?

2025-01-29 22:48 UTC, joaodiaslobo commented on lib/safira/spotlights.ex
> +  end
Also add docs to all public functions

2025-01-29 22:48 UTC, joaodiaslobo commented on lib/safira_web/live/backoffice/spotlights_live/tiers/form_component.ex
> +
Make this way shorter. Like one line.

2025-01-29 22:48 UTC, joaodiaslobo commented on lib/safira_web/live/backoffice/spotlights_live/form_component.ex
> +  This component renders a form for updating the spotlight duration and handles the form submission.
Make this one line only.

2025-01-29 23:36 UTC, joaodiaslobo approved these changes
What a great job! Thank you!! 💙🤘

2025-01-29 23:37 UTC, merged